apiVersion: v1

kind: Pod

metadata:
    name:  myapp-Pod
    namespace: dev
    labels:
        app: myapp

spec:
    containers:
      - name: nginx-container
      - image:  nginx
      name:  my-name
      env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE
